apiVersion: apps/v1
kind: Deployment
metadata:
  name: pandoc-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pandoc-bot
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pandoc-bot
    spec:
      volumes:
        - name: podman-bot-state
          emptyDir: {}
      containers:
        - name: pandoc-bot
          image: kotatsuyaki/pandoc-bot
          imagePullPolicy: Always
          env:
            -
              name: INPUT_BASE_PATH
              value: /inputs
            -
              name: STATE_PATH
              value: /state
            -
              name: AMQP_ADDR
              value: 'amqp://rabbitmq-service:5672'
            -
              name: RUST_LOG
              value: pandoc_bot=info
            -
              name: TELOXIDE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: pandoc-bot-token
                  key: token
          volumeMounts:
            - name: podman-bot-state
              mountPath: /state
              subPath: ''
