apiVersion: apps/v1
kind: Deployment
metadata:
  name: pandoc-bot-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pandoc-bot-worker
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pandoc-bot-worker
    spec:
      containers:
        - name: pandoc-bot-worker
          image: kotatsuyaki/pandoc-bot-worker
          imagePullPolicy: Always
          env:
            -
              name: AMQP_URL
              value: amqp://rabbitmq-service:5672
